// @ts-nocheck
import { Tenant, Charger, ChargingSession, Vehicle, Invoice, AlertNotification, PowerUsageDataPoint } from '../types';

export const MOCK_TENANTS: Tenant[] = [
  {
    tenantId: 'tenant-logitrans',
    companyName: 'LogiTrans Heavy Express',
    siteId: 'site-mw-01',
    billingPlan: 'Tier 3 - Enterprise Demand Response',
    allocatedKwLimit: 220,
    currentKwDemand: 165,
    activeVehiclesCount: 12,
    contactEmail: 'dispatch@logitrans-fleet.com',
    logoColor: 'emerald',
  },
  {
    tenantId: 'tenant-cityexpress',
    companyName: 'CityExpress Courier & Van Co',
    siteId: 'site-mw-01',
    billingPlan: 'Tier 2 - Priority Grid',
    allocatedKwLimit: 150,
    currentKwDemand: 98,
    activeVehiclesCount: 8,
    contactEmail: 'fleet@cityexpress.io',
    logoColor: 'blue',
  },
  {
    tenantId: 'tenant-swiftparcel',
    companyName: 'Swift Parcel Urban Last-Mile',
    siteId: 'site-mw-01',
    billingPlan: 'Tier 1 - Standard',
    allocatedKwLimit: 100,
    currentKwDemand: 49,
    activeVehiclesCount: 6,
    contactEmail: 'operations@swiftparcel.com',
    logoColor: 'purple',
  },
];

export const MOCK_CHARGERS: Charger[] = [
  {
    chargerId: 'CHG-MW-01',
    siteId: 'site-mw-01',
    siteName: 'Metro West Fleet Hub',
    ocppEndpoint: 'ocpp://gw.gridcharge.io/ocpp16j/MW-01',
    maxPower: 120,
    currentKw: 90,
    status: 'charging',
    connectorType: 'CCS2',
    firmwareVersion: 'v2.4.1-ocpp201',
    assignedTenantId: 'tenant-logitrans',
    assignedSessionId: 'SES-901',
  },
  {
    chargerId: 'CHG-MW-02',
    siteId: 'site-mw-01',
    siteName: 'Metro West Fleet Hub',
    ocppEndpoint: 'ocpp://gw.gridcharge.io/ocpp16j/MW-02',
    maxPower: 120,
    currentKw: 45,
    status: 'throttled',
    connectorType: 'CCS2',
    firmwareVersion: 'v2.4.1-ocpp201',
    assignedTenantId: 'tenant-swiftparcel',
    assignedSessionId: 'SES-902',
  },
  {
    chargerId: 'CHG-MW-03',
    siteId: 'site-mw-01',
    siteName: 'Metro West Fleet Hub',
    ocppEndpoint: 'ocpp://gw.gridcharge.io/ocpp16j/MW-03',
    maxPower: 80,
    currentKw: 75,
    status: 'charging',
    connectorType: 'NACS',
    firmwareVersion: 'v2.4.0-ocpp16',
    assignedTenantId: 'tenant-cityexpress',
    assignedSessionId: 'SES-903',
  },
  {
    chargerId: 'CHG-MW-04',
    siteId: 'site-mw-01',
    siteName: 'Metro West Fleet Hub',
    ocppEndpoint: 'ocpp://gw.gridcharge.io/ocpp16j/MW-04',
    maxPower: 150,
    currentKw: 0,
    status: 'occupied',
    connectorType: 'CCS2',
    firmwareVersion: 'v2.5.0-ocpp201',
    assignedTenantId: 'tenant-logitrans',
    assignedSessionId: 'SES-904',
  },
  {
    chargerId: 'CHG-MW-05',
    siteId: 'site-mw-01',
    siteName: 'Metro West Fleet Hub',
    ocppEndpoint: 'ocpp://gw.gridcharge.io/ocpp16j/MW-05',
    maxPower: 60,
    currentKw: 0,
    status: 'available',
    connectorType: 'Type 2',
    firmwareVersion: 'v2.1.0-ocpp16',
  },
  {
    chargerId: 'CHG-MW-06',
    siteId: 'site-mw-01',
    siteName: 'Metro West Fleet Hub',
    ocppEndpoint: 'ocpp://gw.gridcharge.io/ocpp16j/MW-06',
    maxPower: 120,
    currentKw: 0,
    status: 'available',
    connectorType: 'CCS2',
    firmwareVersion: 'v2.4.1-ocpp201',
  },
  {
    chargerId: 'CHG-MW-07',
    siteId: 'site-mw-01',
    siteName: 'Metro West Fleet Hub',
    ocppEndpoint: 'ocpp://gw.gridcharge.io/ocpp16j/MW-07',
    maxPower: 60,
    currentKw: 0,
    status: 'faulted',
    connectorType: 'CHAdeMO',
    firmwareVersion: 'v1.9.8-legacy',
  },
  {
    chargerId: 'CHG-MW-08',
    siteId: 'site-mw-01',
    siteName: 'Metro West Fleet Hub',
    ocppEndpoint: 'ocpp://gw.gridcharge.io/ocpp16j/MW-08',
    maxPower: 150,
    currentKw: 102,
    status: 'charging',
    connectorType: 'CCS2',
    firmwareVersion: 'v2.5.0-ocpp201',
    assignedTenantId: 'tenant-logitrans',
    assignedSessionId: 'SES-905',
  },
];

export const MOCK_SESSIONS: ChargingSession[] = [
  {
    sessionId: 'SES-901',
    chargerId: 'CHG-MW-01',
    siteId: 'site-mw-01',
    vehicleId: 'VEH-LOGI-01',
    tenantId: 'tenant-logitrans',
    tenantName: 'LogiTrans Heavy Express',
    driverName: 'Marcus Vance',
    driverPhone: '+1 (555) 234-5678',
    vehicleModel: 'Volvo VNR Electric Heavy Truck',
    licensePlate: '7X-LOG-88',
    startTime: '2026-08-05T19:30:00Z',
    kWh: 84.5,
    allocatedPower: 90,
    targetPower: 120,
    status: 'charging',
    soc: 68,
    targetSoc: 90,
    batteryCapacityKwh: 264,
    priorityTier: 'critical_delivery',
    departureTime: '22:30',
    etaMinutes: 38,
    costToDate: 29.58,
    ratePerKwh: 0.35,
  },
  {
    sessionId: 'SES-902',
    chargerId: 'CHG-MW-02',
    siteId: 'site-mw-01',
    vehicleId: 'VEH-SWIFT-03',
    tenantId: 'tenant-swiftparcel',
    tenantName: 'Swift Parcel Urban Last-Mile',
    driverName: 'Elena Rostova',
    driverPhone: '+1 (555) 876-5432',
    vehicleModel: 'BrightDrop Zevo 600',
    licensePlate: '9Y-SWF-12',
    startTime: '2026-08-05T20:15:00Z',
    kWh: 32.1,
    allocatedPower: 22,
    targetPower: 80,
    status: 'throttled',
    soc: 54,
    targetSoc: 85,
    batteryCapacityKwh: 165,
    priorityTier: 'overnight_flexible',
    departureTime: '06:00',
    etaMinutes: 110,
    gridThrottledReason: 'Site grid load limit 450 kW reached. Reduced overnight flexible priority rate.',
    costToDate: 11.23,
    ratePerKwh: 0.35,
  },
  {
    sessionId: 'SES-903',
    chargerId: 'CHG-MW-03',
    siteId: 'site-mw-01',
    vehicleId: 'VEH-CITY-07',
    tenantId: 'tenant-cityexpress',
    tenantName: 'CityExpress Courier & Van Co',
    driverName: 'David Chen',
    driverPhone: '+1 (555) 345-6789',
    vehicleModel: 'Ford E-Transit 350',
    licensePlate: '4K-CTY-91',
    startTime: '2026-08-05T21:00:00Z',
    kWh: 19.8,
    allocatedPower: 75,
    targetPower: 80,
    status: 'charging',
    soc: 42,
    targetSoc: 80,
    batteryCapacityKwh: 68,
    priorityTier: 'standard_shift',
    departureTime: '23:15',
    etaMinutes: 32,
    costToDate: 6.93,
    ratePerKwh: 0.35,
  },
  {
    sessionId: 'SES-904',
    chargerId: 'CHG-MW-04',
    siteId: 'site-mw-01',
    vehicleId: 'VEH-LOGI-04',
    tenantId: 'tenant-logitrans',
    tenantName: 'LogiTrans Heavy Express',
    driverName: 'Sarah Jenkins',
    driverPhone: '+1 (555) 456-7890',
    vehicleModel: 'Freightliner eCascadia Class 8',
    licensePlate: '2Z-LOG-44',
    startTime: '2026-08-05T21:40:00Z',
    kWh: 2.0,
    allocatedPower: 0,
    targetPower: 150,
    status: 'connected',
    soc: 24,
    targetSoc: 90,
    batteryCapacityKwh: 438,
    priorityTier: 'critical_delivery',
    departureTime: '04:00',
    etaMinutes: 180,
    costToDate: 0.70,
    ratePerKwh: 0.35,
  },
  {
    sessionId: 'SES-905',
    chargerId: 'CHG-MW-08',
    siteId: 'site-mw-01',
    vehicleId: 'VEH-LOGI-09',
    tenantId: 'tenant-logitrans',
    tenantName: 'LogiTrans Heavy Express',
    driverName: 'Ahmad Al-Mansoor',
    driverPhone: '+1 (555) 998-1122',
    vehicleModel: 'Volvo VNR Electric Heavy Truck',
    licensePlate: '8X-LOG-11',
    startTime: '2026-08-05T18:00:00Z',
    kWh: 140.2,
    allocatedPower: 102,
    targetPower: 150,
    status: 'charging',
    soc: 82,
    targetSoc: 95,
    batteryCapacityKwh: 264,
    priorityTier: 'critical_delivery',
    departureTime: '22:15',
    etaMinutes: 18,
    costToDate: 49.07,
    ratePerKwh: 0.35,
  },
  {
    sessionId: 'SES-906',
    chargerId: 'CHG-MW-05',
    siteId: 'site-mw-01',
    vehicleId: 'VEH-CITY-02',
    tenantId: 'tenant-cityexpress',
    tenantName: 'CityExpress Courier & Van Co',
    driverName: 'Rachel Green',
    driverPhone: '+1 (555) 667-8899',
    vehicleModel: 'Mercedes-Benz eSprinter',
    licensePlate: '5M-CTY-02',
    startTime: '2026-08-05T21:45:00Z',
    kWh: 0,
    allocatedPower: 0,
    targetPower: 60,
    status: 'queued',
    soc: 18,
    targetSoc: 80,
    batteryCapacityKwh: 113,
    priorityTier: 'standard_shift',
    departureTime: '05:30',
    etaMinutes: 120,
    costToDate: 0,
    ratePerKwh: 0.35,
  },
  {
    sessionId: 'SES-900',
    chargerId: 'CHG-MW-06',
    siteId: 'site-mw-01',
    vehicleId: 'VEH-SWIFT-01',
    tenantId: 'tenant-swiftparcel',
    tenantName: 'Swift Parcel Urban Last-Mile',
    driverName: 'Tom Holland',
    driverPhone: '+1 (555) 333-4455',
    vehicleModel: 'Rivian EDV-700 Van',
    licensePlate: '1W-SWF-88',
    startTime: '2026-08-05T16:00:00Z',
    endTime: '2026-08-05T19:10:00Z',
    kWh: 92.4,
    allocatedPower: 0,
    targetPower: 80,
    status: 'complete',
    soc: 100,
    targetSoc: 100,
    batteryCapacityKwh: 135,
    priorityTier: 'standard_shift',
    departureTime: '19:30',
    etaMinutes: 0,
    costToDate: 32.34,
    ratePerKwh: 0.35,
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    vehicleId: 'VEH-LOGI-01',
    tenantId: 'tenant-logitrans',
    tenantName: 'LogiTrans Heavy Express',
    model: 'Volvo VNR Electric Heavy Truck',
    batteryCapacity: 264,
    driver: 'Marcus Vance',
    licensePlate: '7X-LOG-88',
    priorityTier: 'critical_delivery',
    status: 'charging',
  },
  {
    vehicleId: 'VEH-SWIFT-03',
    tenantId: 'tenant-swiftparcel',
    tenantName: 'Swift Parcel Urban Last-Mile',
    model: 'BrightDrop Zevo 600',
    batteryCapacity: 165,
    driver: 'Elena Rostova',
    licensePlate: '9Y-SWF-12',
    priorityTier: 'overnight_flexible',
    status: 'charging',
  },
  {
    vehicleId: 'VEH-CITY-07',
    tenantId: 'tenant-cityexpress',
    tenantName: 'CityExpress Courier & Van Co',
    model: 'Ford E-Transit 350',
    batteryCapacity: 68,
    driver: 'David Chen',
    licensePlate: '4K-CTY-91',
    priorityTier: 'standard_shift',
    status: 'charging',
  },
  {
    vehicleId: 'VEH-LOGI-04',
    tenantId: 'tenant-logitrans',
    tenantName: 'LogiTrans Heavy Express',
    model: 'Freightliner eCascadia Class 8',
    batteryCapacity: 438,
    driver: 'Sarah Jenkins',
    licensePlate: '2Z-LOG-44',
    priorityTier: 'critical_delivery',
    status: 'charging',
  },
  {
    vehicleId: 'VEH-CITY-02',
    tenantId: 'tenant-cityexpress',
    tenantName: 'CityExpress Courier & Van Co',
    model: 'Mercedes-Benz eSprinter',
    batteryCapacity: 113,
    driver: 'Rachel Green',
    licensePlate: '5M-CTY-02',
    priorityTier: 'standard_shift',
    status: 'idle',
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    invoiceId: 'INV-2026-07-LT',
    tenantId: 'tenant-logitrans',
    companyName: 'LogiTrans Heavy Express',
    period: 'July 2026',
    totalKWh: 14850,
    peakKw: 215,
    amount: 5410.50,
    status: 'paid',
    dueDate: '2026-08-15',
    downloadUrl: '#',
    breakdown: {
      baseCharges: 4158.00,
      demandCharges: 1075.00,
      peakPeriodSurcharge: 420.00,
      carbonCreditDiscount: -242.50,
    },
  },
  {
    invoiceId: 'INV-2026-07-CE',
    tenantId: 'tenant-cityexpress',
    companyName: 'CityExpress Courier & Van Co',
    period: 'July 2026',
    totalKWh: 8240,
    peakKw: 135,
    amount: 3012.80,
    status: 'pending',
    dueDate: '2026-08-20',
    downloadUrl: '#',
    breakdown: {
      baseCharges: 2307.20,
      demandCharges: 675.00,
      peakPeriodSurcharge: 180.00,
      carbonCreditDiscount: -149.40,
    },
  },
  {
    invoiceId: 'INV-2026-07-SP',
    tenantId: 'tenant-swiftparcel',
    companyName: 'Swift Parcel Urban Last-Mile',
    period: 'July 2026',
    totalKWh: 5120,
    peakKw: 92,
    amount: 1843.20,
    status: 'paid',
    dueDate: '2026-08-10',
    downloadUrl: '#',
    breakdown: {
      baseCharges: 1433.60,
      demandCharges: 460.00,
      peakPeriodSurcharge: 45.00,
      carbonCreditDiscount: -95.40,
    },
  },
];

export const MOCK_POWER_USAGE_TIMELINE: PowerUsageDataPoint[] = [
  { time: '14:00', totalUsageKw: 180, gridLimitKw: 450, tenantLogiTransKw: 90, tenantCityExpressKw: 55, tenantSwiftParcelKw: 35, solarGenerationKw: 45 },
  { time: '15:00', totalUsageKw: 240, gridLimitKw: 450, tenantLogiTransKw: 120, tenantCityExpressKw: 75, tenantSwiftParcelKw: 45, solarGenerationKw: 50 },
  { time: '16:00', totalUsageKw: 310, gridLimitKw: 450, tenantLogiTransKw: 160, tenantCityExpressKw: 90, tenantSwiftParcelKw: 60, solarGenerationKw: 40 },
  { time: '17:00', totalUsageKw: 390, gridLimitKw: 450, tenantLogiTransKw: 210, tenantCityExpressKw: 110, tenantSwiftParcelKw: 70, solarGenerationKw: 25 },
  { time: '18:00', totalUsageKw: 435, gridLimitKw: 450, tenantLogiTransKw: 220, tenantCityExpressKw: 130, tenantSwiftParcelKw: 85, solarGenerationKw: 10 },
  { time: '19:00', totalUsageKw: 440, gridLimitKw: 450, tenantLogiTransKw: 220, tenantCityExpressKw: 140, tenantSwiftParcelKw: 80, solarGenerationKw: 0 },
  { time: '20:00', totalUsageKw: 380, gridLimitKw: 450, tenantLogiTransKw: 190, tenantCityExpressKw: 120, tenantSwiftParcelKw: 70, solarGenerationKw: 0 },
  { time: '21:00', totalUsageKw: 312, gridLimitKw: 450, tenantLogiTransKw: 165, tenantCityExpressKw: 98, tenantSwiftParcelKw: 49, solarGenerationKw: 0 },
  { time: '22:00', totalUsageKw: 290, gridLimitKw: 450, tenantLogiTransKw: 150, tenantCityExpressKw: 90, tenantSwiftParcelKw: 50, solarGenerationKw: 0 },
];

export const MOCK_NOTIFICATIONS: AlertNotification[] = [
  {
    id: 'notif-1',
    timestamp: 'Just now',
    title: '⚡ Grid Demand Response Engaged',
    message: 'Site grid load approached 450 kW cap. 2 overnight flexible sessions were automatically throttled to protect priority routes.',
    type: 'warning',
    read: false,
  },
  {
    id: 'notif-2',
    timestamp: '12 mins ago',
    title: '✅ Session SES-900 Complete',
    message: 'Rivian EDV-700 (Swift Parcel) completed 100% SoC charge on CHG-MW-06.',
    type: 'success',
    read: false,
  },
  {
    id: 'notif-3',
    timestamp: '45 mins ago',
    title: '🔌 New Vehicle Connected',
    message: 'Freightliner eCascadia plugged into CHG-MW-04 (LogiTrans). Optimization algorithm initialized.',
    type: 'info',
    read: true,
  },
];

export const MOCK_USER_ACCOUNTS: import('../types').UserAccount[] = [
  {
    id: 'usr-admin-01',
    email: 'admin@chargegrid.demo',
    password: 'password123',
    name: 'Elena Rostova',
    role: 'tenant_manager',
    tenant_id: 1,
    tenant_name: 'Charge Grid Admin',
    createdAt: '2026-01-10T08:00:00Z',
    status: 'active',
  },
  {
    id: 'usr-mgr-logitrans',
    email: 'dispatch@logitrans-fleet.com',
    password: 'password123',
    name: 'Marcus Vance',
    role: 'tenant_manager',
    tenantId: 'tenant-logitrans',
    tenantName: 'LogiTrans Heavy Express',
    createdAt: '2026-02-15T10:30:00Z',
    status: 'active',
  },
  {
    id: 'usr-mgr-cityexpress',
    email: 'fleet@cityexpress.io',
    password: 'password123',
    name: 'David Miller',
    role: 'tenant_manager',
    tenantId: 'tenant-cityexpress',
    tenantName: 'CityExpress Courier & Van Co',
    createdAt: '2026-03-01T09:15:00Z',
    status: 'active',
  },
  {
    id: 'usr-driver-sarah',
    email: 'sarah.jenkins@logitrans.com',
    password: 'password123',
    name: 'Sarah Jenkins',
    role: 'driver',
    tenantId: 'tenant-logitrans',
    tenantName: 'LogiTrans Heavy Express',
    vehicleId: 'VEH-LOGI-01',
    vehicleModel: 'Volvo VNR Electric Heavy Duty',
    licensePlate: '1Z-LOG-01',
    createdAt: '2026-04-12T14:20:00Z',
    status: 'active',
  },
  {
    id: 'usr-driver-rachel',
    email: 'rachel.green@cityexpress.io',
    password: 'password123',
    name: 'Rachel Green',
    role: 'driver',
    tenantId: 'tenant-cityexpress',
    tenantName: 'CityExpress Courier & Van Co',
    vehicleId: 'VEH-CITY-02',
    vehicleModel: 'Mercedes-Benz eSprinter',
    licensePlate: '5M-CTY-02',
    createdAt: '2026-05-02T11:00:00Z',
    status: 'active',
  },
];

export const MOCK_ADMIN_REQUESTS: import('../types').AdminRequest[] = [
  {
    id: 'REQ-101',
    type: 'tenant_onboarding',
    title: 'New Logistics Tenant Registration: EcoHaul EV Freight',
    requesterName: 'Arthur Pendelton',
    requesterEmail: 'arthur@ecohaulfreight.com',
    tenantName: 'EcoHaul EV Freight Logistics',
    details: 'Requesting onboarding for 10 heavy class 8 EV trucks at Metro West Hub with 180 kW allocated sub-cap tier.',
    requestedKw: 180,
    createdAt: '2026-08-05T14:30:00Z',
    status: 'pending',
  },
  {
    id: 'REQ-102',
    type: 'power_cap_increase',
    title: 'Temporary Sub-Cap Boost Request (+50 kW)',
    requesterName: 'Marcus Vance',
    requesterEmail: 'dispatch@logitrans-fleet.com',
    tenantId: 'tenant-logitrans',
    tenantName: 'LogiTrans Heavy Express',
    details: 'Urgent express refrigerated trailer charging requirement for overnight long-haul route departure at 06:00 AM.',
    requestedKw: 50,
    createdAt: '2026-08-05T18:15:00Z',
    status: 'pending',
  },
  {
    id: 'REQ-103',
    type: 'driver_access',
    title: 'New EV Driver Registration Approval: Carlos Mendez',
    requesterName: 'Carlos Mendez',
    requesterEmail: 'carlos.mendez@cityexpress.io',
    tenantId: 'tenant-cityexpress',
    tenantName: 'CityExpress Courier & Van Co',
    details: 'New van delivery driver assigned to Mercedes eSprinter (Plate: 6M-CTY-03). Awaiting admin/manager credential activation.',
    createdAt: '2026-08-05T19:40:00Z',
    status: 'pending',
  },
  {
    id: 'REQ-104',
    type: 'charger_fault_report',
    title: 'Maintenance Inspection Request: Charger CHG-MW-07',
    requesterName: 'David Miller',
    requesterEmail: 'fleet@cityexpress.io',
    details: 'CHAdeMO connector locking mechanism error code 403 on Socket 07. Requested maintenance reset or hardware servicing.',
    createdAt: '2026-08-04T09:10:00Z',
    status: 'approved',
    reviewedAt: '2026-08-04T10:00:00Z',
    reviewedBy: 'Elena Rostova',
    adminNotes: 'Dispatched site technician for hardware relay check.',
  },
];

export const calculatePortMetrics = (chargers: import('../types').Charger[]): import('../types').PortMetrics => {
  const totalPorts = chargers.length;
  let occupiedPorts = 0;
  let freePorts = 0;
  let chargingPorts = 0;
  let throttledPorts = 0;
  let faultedPorts = 0;
  let offlinePorts = 0;

  chargers.forEach((c) => {
    if (c.status === 'charging') {
      chargingPorts++;
      occupiedPorts++;
    } else if (c.status === 'throttled') {
      throttledPorts++;
      occupiedPorts++;
    } else if (c.status === 'occupied') {
      occupiedPorts++;
    } else if (c.status === 'available') {
      freePorts++;
    } else if (c.status === 'faulted') {
      faultedPorts++;
    } else if (c.status === 'offline') {
      offlinePorts++;
    }
  });

  const occupancyRatePct = totalPorts > 0 ? Math.round((occupiedPorts / totalPorts) * 100) : 0;

  return {
    totalPorts,
    occupiedPorts,
    freePorts,
    chargingPorts,
    throttledPorts,
    faultedPorts,
    offlinePorts,
    occupancyRatePct,
  };
};

